import { Usuario, Vendedor, Administrador, Cliente, Producto, Venta } from './types';

export const INITIAL_USUARIOS: Usuario[] = [
  {
    id: 'usr_admin_1',
    correo: 'admin@posmodashop.com',
    nombre: 'Carlos Gómez',
    cedula: '1020304050',
    tipo_usuario: 'ADMIN',
  },
  {
    id: 'usr_vend_1',
    correo: 'cajero1@posmodashop.com',
    nombre: 'Laura Restrepo',
    cedula: '1098765432',
    tipo_usuario: 'VENDEDOR',
  },
  {
    id: 'usr_vend_2',
    correo: 'cajero2@posmodashop.com',
    nombre: 'Mateo Valencia',
    cedula: '1152438901',
    tipo_usuario: 'VENDEDOR',
  },
  {
    id: 'usr_cli_0',
    correo: 'mostrador@posmodashop.com',
    nombre: 'Cliente Mostrador (Venta Rápida)',
    cedula: '2222222222',
    tipo_usuario: 'CLIENTE',
  },
  {
    id: 'usr_cli_1',
    correo: 'juliana.gonzalez@example.com',
    nombre: 'Juliana González',
    cedula: '1037654321',
    tipo_usuario: 'CLIENTE',
  },
  {
    id: 'usr_cli_2',
    correo: 'andres.perez@example.com',
    nombre: 'Andrés Pérez',
    cedula: '71234567',
    tipo_usuario: 'CLIENTE',
  },
  {
    id: 'usr_cli_3',
    correo: 'valentina.rios@example.com',
    nombre: 'Valentina Ríos',
    cedula: '1017894561',
    tipo_usuario: 'CLIENTE',
  },
];

export const INITIAL_VENDEDORES: Vendedor[] = [
  {
    id_usuario: 'usr_vend_1',
    codigo_caja: 'CAJA-01',
    turno: 'MAÑANA',
  },
  {
    id_usuario: 'usr_vend_2',
    codigo_caja: 'CAJA-02',
    turno: 'TARDE',
  },
];

export const INITIAL_ADMINISTRADORES: Administrador[] = [
  {
    id_usuario: 'usr_admin_1',
    cargo: 'Gerente General & Operaciones',
    dinero_en_cuenta: 18540000,
  },
];

export const INITIAL_CLIENTES: Cliente[] = [
  {
    id_usuario: 'usr_cli_0',
    cedula: '2222222222',
    nombre: 'Cliente Mostrador (Venta Rápida)',
    telefono: '3000000000',
    direccion: 'Punto de Venta Central',
  },
  {
    id_usuario: 'usr_cli_1',
    cedula: '1037654321',
    nombre: 'Juliana González',
    telefono: '3104567890',
    direccion: 'Cra 43A #1-50, Apto 402, Medellín',
  },
  {
    id_usuario: 'usr_cli_2',
    cedula: '71234567',
    nombre: 'Andrés Pérez',
    telefono: '3157891234',
    direccion: 'Calle 50 #70-25, Envigado',
  },
  {
    id_usuario: 'usr_cli_3',
    cedula: '1017894561',
    nombre: 'Valentina Ríos',
    telefono: '3209876543',
    direccion: 'Circular 4 #73-10, Laureles',
  },
];

export const INITIAL_PRODUCTOS: Producto[] = [
  {
    id_producto: 'PROD-001',
    nombre: 'Camiseta Oversize Heavy Cotton',
    genero: 'Unisex',
    talla: 'M',
    cantidad_stock: 14,
    precio: 65000,
    categoria: 'Camisetas',
    codigo_barras: '7701001001',
  },
  {
    id_producto: 'PROD-002',
    nombre: 'Camiseta Oversize Heavy Cotton',
    genero: 'Unisex',
    talla: 'L',
    cantidad_stock: 8,
    precio: 65000,
    categoria: 'Camisetas',
    codigo_barras: '7701001002',
  },
  {
    id_producto: 'PROD-003',
    nombre: 'Jean Slim Fit Denim Índigo',
    genero: 'Hombre',
    talla: '38',
    cantidad_stock: 6,
    precio: 139900,
    categoria: 'Pantalones',
    codigo_barras: '7701001003',
  },
  {
    id_producto: 'PROD-004',
    nombre: 'Jean Mom Fit Tiro Alto Vintage',
    genero: 'Mujer',
    talla: 'S',
    cantidad_stock: 5,
    precio: 145000,
    categoria: 'Pantalones',
    codigo_barras: '7701001004',
  },
  {
    id_producto: 'PROD-005',
    nombre: 'Buzo Hoodie Casual Friso',
    genero: 'Unisex',
    talla: 'L',
    cantidad_stock: 3, // Stock bajo para probar alerta
    precio: 125000,
    categoria: 'Buzos',
    codigo_barras: '7701001005',
  },
  {
    id_producto: 'PROD-006',
    nombre: 'Vestido Midi Lino Estampado',
    genero: 'Mujer',
    talla: 'M',
    cantidad_stock: 7,
    precio: 110000,
    categoria: 'Vestidos',
    codigo_barras: '7701001006',
  },
  {
    id_producto: 'PROD-007',
    nombre: 'Camisa Manga Corta Bowling',
    genero: 'Hombre',
    talla: 'M',
    cantidad_stock: 9,
    precio: 89000,
    categoria: 'Camisas',
    codigo_barras: '7701001007',
  },
  {
    id_producto: 'PROD-008',
    nombre: 'Chaqueta Bomber Impermeable',
    genero: 'Unisex',
    talla: 'XL',
    cantidad_stock: 4,
    precio: 195000,
    categoria: 'Chaquetas',
    codigo_barras: '7701001008',
  },
  {
    id_producto: 'PROD-009',
    nombre: 'Gorra Trucker Bordada Vintage',
    genero: 'Unisex',
    talla: 'Única',
    cantidad_stock: 20,
    precio: 45000,
    categoria: 'Accesorios',
    codigo_barras: '7701001009',
  },
  {
    id_producto: 'PROD-010',
    nombre: 'Top Deportivo Seamless Alto Soporte',
    genero: 'Mujer',
    talla: 'S',
    cantidad_stock: 1, // Última unidad
    precio: 55000,
    categoria: 'Deportivo',
    codigo_barras: '7701001010',
  },
  {
    id_producto: 'PROD-011',
    nombre: 'Short Cargo Safari Drill',
    genero: 'Hombre',
    talla: 'M',
    cantidad_stock: 0, // Agotado para probar validación
    precio: 78000,
    categoria: 'Bermudas',
    codigo_barras: '7701001011',
  },
];

export const INITIAL_VENTAS: Venta[] = [
  {
    id_venta: 'VENTA-1001',
    fecha: '2026-09-09 10:15',
    medio_pago: 'DATAFONO',
    canal: 'FISICO',
    subtotal: 172269,
    impuesto: 32731,
    total: 205000,
    id_cliente: 'usr_cli_1',
    cliente_nombre: 'Juliana González',
    cliente_cedula: '1037654321',
    id_vendedor: 'usr_vend_1',
    vendedor_nombre: 'Laura Restrepo',
    codigo_caja: 'CAJA-01',
    items: [
      {
        id_producto: 'PROD-001',
        nombre: 'Camiseta Oversize Heavy Cotton',
        talla: 'M',
        cantidad: 1,
        precio_unitario: 65000,
        subtotal: 65000,
      },
      {
        id_producto: 'PROD-003',
        nombre: 'Jean Slim Fit Denim Índigo',
        talla: '38',
        cantidad: 1,
        precio_unitario: 140000,
        subtotal: 140000,
      },
    ],
  },
  {
    id_venta: 'VENTA-1002',
    fecha: '2026-09-09 14:30',
    medio_pago: 'NEQUI',
    canal: 'VIRTUAL',
    subtotal: 105042,
    impuesto: 19958,
    total: 125000,
    id_cliente: 'usr_cli_2',
    cliente_nombre: 'Andrés Pérez',
    cliente_cedula: '71234567',
    id_vendedor: 'usr_vend_1',
    vendedor_nombre: 'Laura Restrepo',
    codigo_caja: 'CAJA-01',
    notas: 'Pedido WhatsApp - Despacho a Envigado',
    items: [
      {
        id_producto: 'PROD-005',
        nombre: 'Buzo Hoodie Casual Friso',
        talla: 'L',
        cantidad: 1,
        precio_unitario: 125000,
        subtotal: 125000,
      },
    ],
  },
  {
    id_venta: 'VENTA-1003',
    fecha: '2026-09-09 16:45',
    medio_pago: 'EFECTIVO',
    canal: 'FISICO',
    subtotal: 37815,
    impuesto: 7185,
    total: 45000,
    pago_recibido: 50000,
    cambio: 5000,
    id_cliente: 'usr_cli_0',
    cliente_nombre: 'Cliente Mostrador (Venta Rápida)',
    cliente_cedula: '2222222222',
    id_vendedor: 'usr_vend_2',
    vendedor_nombre: 'Mateo Valencia',
    codigo_caja: 'CAJA-02',
    items: [
      {
        id_producto: 'PROD-009',
        nombre: 'Gorra Trucker Bordada Vintage',
        talla: 'Única',
        cantidad: 1,
        precio_unitario: 45000,
        subtotal: 45000,
      },
    ],
  },
];
